{% set name = "napari-pixel-correction" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-pixel-correction-{{ version }}.tar.gz
  sha256: b08823fa39eb69d937e651bb04e7fb4c013e9059bee5ff43fa2e0849851a9a3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - scikit-image

test:
  imports:
    - napari_pixel_correction
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hereariim/napari-pixel-correction
  summary: Plugin to correct manually pixel wrongly predicted on image by annotation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hereariim
    - jaimergp
